# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Langue par défaut : français uniquement
fr:
  languageName: Français
  locale: fr-ma
  weight: 1
